[package]
name = "shared"
version = "0.1.1"
edition = "2024"

[dependencies]
color-eyre = "0.6.5"
tokio = { version = "1.49.0",features = ["full"] }
reedline = { version = "0.45.0", features = ["external_printer"] }